Added a reply feature
white-van/WVAnonBot pull request #9
Opened 2020-12-31 00:37 UTC by CometWhoosh

### What's new?
I added a reply feature that lets users reply to messages by DMing the bot with `!send/send-deep reply {message number} {message}`. The reply can be made NSFW by including the `nsfw` command: `!send/send-deep nsfw reply {message number} {message}`.

A reply includes a link to the message being replied to, followed by a quote block that contains the message being replied to. If the message is 130 characters or longer, then it will be cutoff at the 130th character and the quote block will end in ellipses.

### Why make this change?
This feature improves readability—replies are clear and easy to read. By having the message being replied to in a quote block, users don't have to scroll up to find out what was said. And if the message is cut off in the quote block with ellipses, the link will allow users to jump to the message and read it for themselves.

### How is this done?
A new table, `messages`, is used to keep track of message numbers, the content of messages, and their urls. Any code that used to update the table `messageCounter` has been replaced to update `messages` instead. The act of replying is handled in `bot.js`. To ensure that users only reply to messages sent after this update, a new error (`2011`)  was added in `errors.js`.

2020-12-31 06:23 UTC, jcserv requested changes
Awesome job! The functionality looks great, just a few areas of improvement:
1. The !send reply command instructions are not in help, check out errors.js
2. Try replying to a message that is not in the new table, you'll get this runtime error:

![fdsfdsfdsfdsfsd](https://user-images.githubusercontent.com/45128231/103397462-81881c00-4b06-11eb-9574-69997c8fbb38.PNG)

3. Try sending an improperly formatted message like `!send reply nsfw hey`
![Capture](https://user-images.githubusercontent.com/45128231/103397496-abd9d980-4b06-11eb-8fbf-7b7f9870c1ee.PNG)

2021-01-01 01:05 UTC, jcserv approved these changes
Great work!! ✨

2021-01-02 00:03 UTC, SergeyGV commented
Took a look and gave it a run-through. You've done some solid work, well done. I have not located any bugs when testing normally or through an older db for upgrade. There's a few things I'd love to see addressed before we throw this into live

1. Remove the .idea files from your commit

2. If I'm understanding correctly, you've phased out the `messageCounter` table completely, save for retrieving the last stored number in there for your table on the first time someone saves a message. If that's the case, clean up the code and remove everything that had to do with that table(with your code interaction excluded). Leave a quick comment as well in the area you work with as to what happened with it, just so we remember what it was for the future

3. The `!help` command for users is looking packed now, and it's hard to parse visually anymore. Split up the commands into more categories with fields(for example, see the "!anon help" text available to mods/admins)

4. Personal preference, but something that I want to try and enforce in the future to keep our code base clean: when you have everything finished, can you squash all of your commits into one? This helps us keep the branch clean and distinctly see what came in and where. For bug fixes we don't need that, but for feature implementations it's best to keep it easily visible where it all came from. @jcserv As a heads up to you as well on that

2021-01-02 23:34 UTC, SergeyGV approved these changes

2021-01-02 23:37 UTC, merged